language: cpp

compiler:
  - gcc

# by default Ubuntu Precise is included
# this results on 3 build configurations:
# Ubuntu Precise and Trusty + Latest OSX image
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: bionic
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode11

addons:
  apt:
    packages:
      - cmake
      - qt5-default
      - libqt5opengl5-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libprotobuf-dev 
      - protobuf-compiler 
      - libode-dev
      - libboost-dev
  homebrew:
    taps: robotology/formulae
    packages:
      - qt5
      - protobuf
      - robotology/formulae/ode

install:
  # vartypes
  - git clone https://github.com/jpfeltracco/vartypes.git
  - cd vartypes
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install

script:
  # grsim
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
